### ISSUE TITLE
Event downloads broken in v2

### ISSUE THREAD

**Issue by tauren** [unifi-toolbox/unifi-protect-video-downloader#29]
Awesome work on this project! Thank you!

I have v1 working properly for downloading blocks of time. I'd like to get event downloading working, so I'm attempting to run v2. However I am only getting errors. Any thoughts?

# Get events from all cameras

```
$ docker run --volume ~/v2-downloads:/downloads unifitoolbox/protect-archiver events --address=10.10.10.2 --username="unifi-toolbox" --password="*****" --cameras="all" --start="2020-05-28 08:30:00-0700" --end="2020-05-28 21:30:00-0700" --skip-existing-files --download-motion-heatmaps /downloads

Getting camera list
Successfully authenticated as user unifi-toolbox
Successfully retrieved data from /api/cameras
Getting motion event list
Cameras found:
- Int Front Door (5ea51d31010bc103e7000583)
- Ext Front Porch (5ea3de9503364c03e7000435)
- Int Garage (5e98294602216d03e70003fe)
- Ext Garage Yard (5e982b26008f6d03e700040b)
- Int Front Room (5ea528de02dfc103e70006f8)
- Int Kitchen Birdseye (5eceb41403e6fd03e7000487)
- Int Main Bath (Was Kitchen) (5eaba4be01302303e70005f0)
- Int Sunroom (Was Front Window) (5ea4f3f100046d03e7000478)
- Ext Side Porch (5ea3de9600034c03e7000436)
Successfully retrieved data from /api/events
Downloading motion event video files between 2020-05-28 08:30:00-07:00 and 2020-05-28 21:30:00-07:00 from 'https://10.10.10.2:7443/api/video/export'

324 motion events found between 2020-05-28 08:30:00-07:00 and 2020-05-28 21:30:00-07:00
Traceback (most recent call last):
  File "/usr/local/bin/protect-archiver", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/__init__.py", line 20, in main
    cli.main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/events.py", line 174, in events
    [c for c in camera_list if c['id'] == motion_event.camera_id][0],  # get camera from list of cameras by id
IndexError: list index out of range
```

# Get events for one camera

```
$ docker run --volume ~/v2-downloads:/downloads unifitoolbox/protect-archiver events --address=10.10.10.2 --username="unifi-toolbox" --password="*****" --cameras="5ea3de9600034c03e7000436" --start="2020-05-28 08:30:00-0700" --end="2020-05-28 21:30:00-0700" --skip-existing-files --download-motion-heatmaps /downloads

Getting camera list
Successfully authenticated as user unifi-toolbox
Successfully retrieved data from /api/cameras
Getting motion event list
Cameras found:
- Int Front Door (5ea51d31010bc103e7000583)
- Ext Front Porch (5ea3de9503364c03e7000435)
- Int Garage (5e98294602216d03e70003fe)
- Ext Garage Yard (5e982b26008f6d03e700040b)
- Int Front Room (5ea528de02dfc103e70006f8)
- Int Kitchen Birdseye (5eceb41403e6fd03e7000487)
- Int Main Bath (Was Kitchen) (5eaba4be01302303e70005f0)
- Int Sunroom (Was Front Window) (5ea4f3f100046d03e7000478)
- Ext Side Porch (5ea3de9600034c03e7000436)
Successfully retrieved data from /api/events
324 motion events found between 2020-05-28 08:30:00-07:00 and 2020-05-28 21:30:00-07:00
Traceback (most recent call last):
  File "/usr/local/bin/protect-archiver", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/__init__.py", line 20, in main
    cli.main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/events.py", line 161, in events
    motion_event_list = [
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/events.py", line 162, in <listcomp>
    e for e in motion_event_list if e["camera_id"] in cameras
TypeError: 'MotionEvent' object is not subscriptable
```

**Comment by danielfernau** [comment]
Hi @tauren – thanks for the great feedback and for reporting this issue!

Just pushed commit b375901e99927adbad47ef292113a8ce7f701954 which should resolve the second error. The Docker image has been updated accordingly, so you can test the new release right away (latest image is now [7f607dfb582e](https://hub.docker.com/layers/unifitoolbox/protect-archiver/latest/images/sha256-7f607dfb582e26d8ca0ce3e7b56a2a3474d47a175dfa160a12669521b276d860?context=explore)).

Please let me know if this also fixes the first error, as I was unable to replicate the 'list index out of range' situation on my test system over here.

**Comment by tauren** [comment]
@danielfernau I pulled the latest image with `docker pull unifitoolbox/protect-archiver`. Now when I specify `all` cameras as well as a single camera, it doesn't crash. I haven't tested extensively, but it looks like the problem is resolved. Thank you!

I did notice a couple other issues:

#  Local vs GMT time

Downloaded event filename and folders appear to be in GMT time, not the timezone specified in the `start` and `end` options. For instance, I've specified `-0700` (Pacific Time) in start and end and have an event that starts June 3, 2020 at 05:04:05pm PST. This event gets saved into the file `2020/06/04/Camera Name/Camera Name - 2020-06-04 - 01:04:05.mp4`.

Maybe this is by design? But it was unexpected, especially since v1 behaved differently.

# Confusing event reporting

This is a super minor concern, but wanted to mention it.

I've specified a single camera, but the reporting indicates the event count for all cameras. It then reports that no events were downloaded. It turns out the camera I specified had no events during that timeframe, but the reporting doesn't make this obvious.

```
$ docker run --volume ~/v2-downloads:/downloads unifitoolbox/protect-archiver events --address=10.10.10.2 --username="unifi-toolbox" --password="****" --cameras="5ea3de9600034c03e7000436" --start="2020-06-03 08:30:00-0700" --end="2020-06-03 21:30:00-0700" --skip-existing-files /downloads
Getting camera list
Successfully authenticated as user unifi-toolbox
Successfully retrieved data from /api/cameras
Getting motion event list
Cameras found:
- Int Sunroom (Was Front Window) (5ea4f3f100046d03e7000478)
- Int Garage (5e98294602216d03e70003fe)
- Int Kitchen Birdseye (5eceb41403e6fd03e7000487)
- Int Front Door (5ea51d31010bc103e7000583)
- Ext Front Porch (5ea3de9503364c03e7000435)
- Ext Side Yard South (5ed4894702705b03e7000691)
- Int Main Bath (Was Kitchen) (5eaba4be01302303e70005f0)
- Ext Garage Yard (5e982b26008f6d03e700040b)
- Int Front Room (5ea528de02dfc103e70006f8)
- Ext Driveway (5ed4698f00a5b403e70009c7)
- Ext Side Porch (5ea3de9600034c03e7000436)
- Ext Backyard New (5ed46682018bb403e7000992)
Successfully retrieved data from /api/events
37 motion events found between 2020-06-03 08:30:00-07:00 and 2020-06-03 21:30:00-07:00
Downloading motion event video files between 2020-06-03 08:30:00-07:00 and 2020-06-03 21:30:00-07:00 from 'https://10.10.10.2:7443/api/video/export'

0 files downloaded (0.0 b), 0 files skipped, 0 files total
```

**Comment by danielfernau** [comment]
@tauren Thanks for testing and the feedback! 

I just created two new issues for your suggestions. Both – being able to select between local and GMT for the file name timestamp as well as making the event count in console output clearer for individual cameras – are very good ideas.

I'll close this issue for now as it seems to be resolved. But feel free to re-open it if necessary.
