### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by superforno** [unifi-toolbox/unifi-protect-video-downloader#36]
Hello, using UDM-Pro and v. 2.0 with events command, I'm having this new error:

`Downloading motion event 9dd1 at 2020-10-11 02:21:43.411000 for camera 'Esterno F' (5f2aec5900205f0387001a0d) to /downloads/2020/10/11/Esterno F (1a0d)/Esterno F (1a0d) - 2020-10-11 - 02.21.43.mp4
Traceback (most recent call last):
  File "/usr/local/bin/protect-archiver", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/__init__.py", line 20, in main
    cli.main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/events.py", line 184, in events
    client.download_motion_event(
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/client.py", line 492, in download_motion_event
    self.download_file(address, filename)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/client.py", line 175, in download_file
    data.get("error") or data or "(no information available)"
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by danielfernau** [comment]
Related to #33

**Comment by danielfernau** [comment]
Hi @superforno 

A new release – [v2.0.1](https://github.com/unifi-toolbox/unifi-protect-video-downloader/releases/tag/v2.0.1) – is now available. Please have a look if the problem you've reported here still occurs.
